language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script:
  - composer self-update || true
  - composer --prefer-source --dev install

script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php --configuration phpunit.xml