language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update || true
  - composer --prefer-source --dev install

script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php --configuration phpunit.xml